### ISSUE TITLE
Incorrect Format specifier when printing 

### ISSUE THREAD

**Issue by williamsimms** [Sekaiw0w/The-Commits#1]
The user is prompted to enter 2 floating point numbers , the sum is then calculated and then printed using the %i Format specifier . The %i along with the %d format specifiers are used with integer data types. This results in a loss of precision .

**Comment by Sekaiw0w** [comment]
Thank you. I will make the necessary changes as fast as I can.

**Comment by williamsimms** [comment]
Also the import of the Standard library header file is completely unnecessary.

**Comment by williamsimms** [comment]
Hello?

**Comment by Sekaiw0w** [comment]
Hi William

I’ve only just received these messages. I am not too sure why they did not
come through before. However, as you know, the issue has been resolved.

Thank you for your assistance.

With Regards,
Sekai Smart-Macaulay
